name: Run test scripts

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install bchosttrust
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Run test scripts
      run: |
        python -m unittest discover -s tests -p "*.py" -v
